main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Fees__c/Product_Fees__c.object-meta.xml
<CustomObject>
    <label>Product Fees</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Product_Fees__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost per Calendar Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Product_Fees__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <label>Fees</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Fees__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Product_Fees__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_List</valueSetName>
    </valueSet>
</CustomField>

main/default/globalValueSets/Home_Country_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country List</masterLabel>
</GlobalValueSet>

main/default/globalValueSets/Product_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product List</masterLabel>
</GlobalValueSet>

main/default/classes/ContactProductDetails.cls
/****************************************************************************************************
Class    :  ContactProductDetails
Developer:  Praful
Created  :  Feburary 23, 2023
Objective:  This class provides Apex REST Methods like HttpGet for external service to get Product Fees details and implement global class
ChangeHistory: 
****************************************************************************************************/
@RestResource(urlMapping = '/product-fees-management/contact/*')
global class ContactProductDetails {
    
    /*************************************************************
    Method   :  getProductFees
    Developer:  Praful
    Objective:  This method will accept UUID as paremeter in endpoint and get associated conatct and fees datails based on contact Product and home country  
    *************************************************************/
    
    @HttpGet
    global static list<customProductFees> getProductFees() 
    {
        RestRequest req = RestContext.request;
        String contactId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        system.debug('xc' + contactId);
        if(contactId != null){        
            List<Product_Fees__c> clientrelatedProductFees = new    List<Product_Fees__c> ();
            // fetch contact's Product__c and Home_Country__c
            List<contact> listContact = [SELECT Id, Product__c, Home_Country__c
                                         FROM contact
                                         WHERE UUID__c = :contactId LIMIT 1];
            
            if(listContact.size() > 0){ 
                //based on contact Product__c and Home_Country__c get fees detail from Product_Fees__c custom object
                if(listContact[0].Product__c != null && listContact[0].Home_Country__c != null){
                    
                    List<customProductFees> clientrelatedProductFeesWrapper = new    List<customProductFees> (); 
                    clientrelatedProductFees = [SELECT id, Fees__c, CurrencyIsoCode, Home_Country__c, Cost_Type__c, Product_Type__c
                                                FROM Product_Fees__c
                                                WHERE Product_Type__c =: listContact[0].Product__c and Home_Country__c =: listContact[0].Home_Country__c ];
                    
                    
                    if(clientrelatedProductFees.size() > 0){                   
                        for (Product_Fees__c pf : clientrelatedProductFees){
                            if(!pf.Fees__c.isNumeric()){
                                clientrelatedProductFeesWrapper.add(new customProductFees(pf.Cost_Type__c, pf.Home_Country__c, pf.Fees__c, pf.Product_Type__c ));
                            } else{
                                String feesWithCurrency = pf.CurrencyIsoCode + ' ' + pf.Fees__c;
                                clientrelatedProductFeesWrapper.add(new customProductFees(pf.Cost_Type__c, pf.Home_Country__c, feesWithCurrency, pf.Product_Type__c ));
                            }
                        }
                    }  
                    return clientrelatedProductFeesWrapper;         
                }
            }
            
        }
        return null;      
    }
    
    global class customProductFees{
        
        @AuraEnabled public String costType;
        @AuraEnabled public String homeCountry;
        @AuraEnabled public String fees;
        @AuraEnabled public String productType;
        
        public customProductFees(string costType, string homeCountry, string fees, string productType ){
            this.costType = costType;
            this.homeCountry = homeCountry;
            this.fees = fees;
            this.productType = productType;
        }    
    }
    
}