main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Product_Fees__c/Product_Fees__c.object-meta.xml
<CustomObject>
    <label>Product Fees</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Product_Fees__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost per Calendar Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Product_Fees__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <label>Fees</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Fees__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Product_Fees__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_List</valueSetName>
    </valueSet>
</CustomField>

main/default/globalValueSets/Home_Country_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country List</masterLabel>
</GlobalValueSet>

main/default/globalValueSets/Product_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product List</masterLabel>
</GlobalValueSet>

main/default/classes/ProductFeesDetailsController.cls
/****************************************************************************************************
Class    :  ProductFeesDetailsController
Developer:  Praful
Created  :  Feburary 23, 2023
Objective:  This class provides methods for contactOnCaseProductFees LWC
ChangeHistory: 
****************************************************************************************************/

public with sharing class ProductFeesDetailsController {
    
   /*************************************************************
    Method   :  fetchClientFees
    Developer:  Praful
    Objective:  This method will fetch Product_Fees__c details from custom object based on contact associated to case
    *************************************************************/
  
    @AuraEnabled(cacheable=true)
    public static List<customProductFees> fetchClientFees(string caseId) {
        List<Product_Fees__c> clientrelatedProductFees = new    List<Product_Fees__c> ();
        // fetch contact on case Product__c and Home_Country__c
        List<Case> listCase = [SELECT Id, Contact.Product__c, Contact.Home_Country__c
                              FROM Case
                              WHERE Id = :caseId LIMIT 1];
        
        if(listCase.size() > 0){ 
            //based on contact on case Product__c and Home_Country__c get fees detail from Product_Fees__c custom object
            if(listCase[0].Contact.Product__c != null && listCase[0].Contact.Home_Country__c != null){

                List<customProductFees> clientrelatedProductFeesWrapper = new    List<customProductFees> ();

                
                clientrelatedProductFees = [SELECT id, Fees__c, CurrencyIsoCode, Home_Country__c, Cost_Type__c, Product_Type__c
                                            FROM Product_Fees__c
                                            WHERE Product_Type__c =: listCase[0].Contact.Product__c and Home_Country__c =: listCase[0].Contact.Home_Country__c ];
                
                
                if(clientrelatedProductFees.size() > 0){                   
                    for (Product_Fees__c pf : clientrelatedProductFees){
                        if(!pf.Fees__c.isNumeric()){
                            clientrelatedProductFeesWrapper.add(new customProductFees(pf.Cost_Type__c, pf.Home_Country__c, pf.Fees__c, pf.Product_Type__c ));
                        } else{
                            String feesWithCurrency = pf.CurrencyIsoCode + ' ' + pf.Fees__c;
                            clientrelatedProductFeesWrapper.add(new customProductFees(pf.Cost_Type__c, pf.Home_Country__c, feesWithCurrency, pf.Product_Type__c ));
                        }
                    }
                }  
                return clientrelatedProductFeesWrapper;         
            }
        }
       return null;                         
    }
    
    public class customProductFees{
        
        @AuraEnabled public String costType;
        @AuraEnabled public String homeCountry;
        @AuraEnabled public String fees;
        @AuraEnabled public String productType;
        
        public customProductFees(string costType, string homeCountry, string fees, string productType ){
            this.costType = costType;
            this.homeCountry = homeCountry;
            this.fees = fees;
            this.productType = productType;
        }    
    }
}