main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Fees__c/Product_Fees__c.object-meta.xml
<CustomObject>
    <label>Product Fees</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Product_Fees__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost per Calendar Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Product_Fees__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <label>Fees</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Fees__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country_List</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Product_Fees__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_List</valueSetName>
    </valueSet>
</CustomField>

main/default/globalValueSets/Home_Country_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country List</masterLabel>
</GlobalValueSet>

main/default/globalValueSets/Product_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product List</masterLabel>
</GlobalValueSet>

main/default/classes/ContactProductDetails_Test.cls
@isTest
Private class ContactProductDetails_Test {
    @testsetup
    static void testDataCreation(){
        
        Account acc = new Account();
        acc.name = 'test acc';
        acc.BillingCity = 'test city';
        acc.billingState = 'test state';
        insert acc;
        
        Contact cont = new Contact();
        cont.FirstName = 'test';
        cont.LastName = 'cont';
        cont.Email = 'testEmail@testPg.com';
        cont.AccountId = acc.Id;
        cont.Product__c = 'Standard';
        cont.Home_Country__c = 'DE';
        cont.uuid__c = '1111';
        insert cont;
        
        Case cs = new Case();
        cs.subject = 'test subject';
        cs.Description = 'test description';
        cs.ContactId = cont.id;
        cs.Status = 'New';
        cs.Origin = 'Email';
        insert cs;
        
        Product_Fees__c pfee = new Product_Fees__c();
        pfee.name = 'test rec';
        pfee.Cost_Type__c = 'Cost per Calendar Month';
        pfee.Home_Country__c = 'DE';
        pfee.Fees__c =  '10';
        pfee.Product_Type__c = 'Standard';
        insert pfee;
        
        Product_Fees__c pfee1 = new Product_Fees__c();
        pfee1.name = 'test rec2';
        pfee1.Cost_Type__c = 'Cost per Calendar Month';
        pfee1.Home_Country__c = 'DE';
        pfee1.Fees__c =  '10';
        pfee1.Product_Type__c = 'Metal';
        insert pfee1;
        
        Product_Fees__c pfee2 = new Product_Fees__c();
        pfee2.name = 'test rec2';
        pfee2.Cost_Type__c = 'Cost per Calendar Month';
        pfee2.Home_Country__c = 'DE';
        pfee2.Fees__c =  '10';
        pfee2.Product_Type__c = 'Black';
        insert pfee2;
        
    }   
    
    @isTest
    static void getProductFees_Test(){        
        
      // Set up a test request
        RestRequest request = new RestRequest();
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        request.requestUri = baseUrl + '/services/apexrest/product-fees-management/contact/' + '111';
        request.httpMethod = 'GET';
        RestContext.request = request;
        // Call the method to test
         List<ContactProductDetails.customProductFees> custFees = ContactProductDetails.getProductFees();
        // Verify results
        System.assert(custFees != null);
        System.assertEquals(custFees[0].fees, 'EUR 10','test');

     
    }
    
}